# Navigation Links
main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /#publications
    weight: 20
  - name: Projects
    url: /#projects
    weight: 30
  - name: CV
    url: cv/
    weight: 40
  - name: Writing
    url: /post
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
