#!/usr/bin/env python3
"""Generate src/data/world-strip.ts: an inline SVG coastline path for the
RouteStrip component, plus the three research-site coordinates projected
into the same viewBox.

Source: Natural Earth 110m coastline (public domain), same footing as
scripts/sample-canopy-pointcloud.py's data provenance. Clips to the Atlantic
window (lon -85..25, lat -40..65) that holds all three sites, then
Douglas-Peucker simplifies so the inline path stays under the check-build
budget (8 KB).
"""
import json
from pathlib import Path

import geopandas as gpd
from shapely.geometry import box

SHP = Path.home() / ".cache/naturalearth/ne_110m_coastline.shp"
OUT = Path(__file__).resolve().parent.parent / "src/data/world-strip.ts"

LON_MIN, LON_MAX = -85, 25
LAT_MIN, LAT_MAX = -40, 65
SCALE = 8  # user units per degree — plain equirectangular, no cosine correction
TOLERANCE_DEG = 0.12  # Douglas-Peucker tolerance, in degrees, pre-projection

PLACES = [
    {"id": "rio", "name": "Rio de Janeiro", "lat": -22.993, "lon": -43.240},
    {"id": "amsterdam", "name": "Amsterdam", "lat": 52.378, "lon": 4.880},
    {"id": "stata", "name": "Cambridge, MA", "lat": 42.362, "lon": -71.091},
]


def project(lon, lat):
    x = (lon - LON_MIN) * SCALE
    y = (LAT_MAX - lat) * SCALE
    return x, y


def build_path(simplified_geoms):
    parts = []
    vertex_count = 0
    for geom in simplified_geoms:
        if geom is None or geom.is_empty:
            continue
        lines = [geom] if geom.geom_type == "LineString" else list(getattr(geom, "geoms", []))
        for line in lines:
            if line.geom_type != "LineString":
                continue
            pts = [project(lon, lat) for lon, lat in line.coords]
            pts = [(round(x), round(y)) for x, y in pts]
            dedup = [pts[0]]
            for p in pts[1:]:
                if p != dedup[-1]:
                    dedup.append(p)
            if len(dedup) < 2:
                continue
            vertex_count += len(dedup)
            d = f"M{dedup[0][0]} {dedup[0][1]}" + "".join(f"L{x} {y}" for x, y in dedup[1:])
            parts.append(d)
    return " ".join(parts), vertex_count


def main():
    gdf = gpd.read_file(SHP)
    clip_box = box(LON_MIN, LAT_MIN, LON_MAX, LAT_MAX)
    clipped = gdf.clip(clip_box)
    simplified = clipped.geometry.simplify(TOLERANCE_DEG, preserve_topology=True)

    path, vertex_count = build_path(simplified)
    path_bytes = len(path.encode("utf-8"))
    print(f"world-strip path: {path_bytes} bytes, {vertex_count} vertices, tolerance={TOLERANCE_DEG} deg")
    if path_bytes >= 8 * 1024:
        raise SystemExit(f"path is {path_bytes} bytes — over the 8 KB budget, raise TOLERANCE_DEG")

    width = round((LON_MAX - LON_MIN) * SCALE)
    height = round((LAT_MAX - LAT_MIN) * SCALE)

    places_out = []
    for p in PLACES:
        x, y = project(p["lon"], p["lat"])
        places_out.append(
            {
                "id": p["id"],
                "name": p["name"],
                "lat": p["lat"],
                "lon": p["lon"],
                "x": round(x, 1),
                "y": round(y, 1),
            }
        )

    ts = f"""// Generated by scripts/make-world-strip.py — do not hand-edit.
// Source: Natural Earth 110m coastline (public domain), clipped to lon
// {LON_MIN}..{LON_MAX} lat {LAT_MIN}..{LAT_MAX} and Douglas-Peucker simplified
// (tolerance {TOLERANCE_DEG} deg) to keep the inline path under the check-build
// 8 KB budget. Equirectangular: x = (lon - {LON_MIN}) * {SCALE}, y = ({LAT_MAX} - lat) * {SCALE}.
export const worldStripViewBox = '0 0 {width} {height}';
export const worldStripWidth = {width};
export const worldStripHeight = {height};
export const worldStripPath = '{path}';
export const worldStripPlaces = {json.dumps(places_out, indent=2)} as const;
"""
    OUT.write_text(ts)
    print(f"wrote {OUT} ({len(ts.encode('utf-8'))} bytes total)")


if __name__ == "__main__":
    main()
